### ISSUE TITLE
What's the plan going forward?

### ISSUE THREAD

**Issue by alixander** [dagrejs/dagre#352]
Exciting to see the deprecated warning being removed and the recent activity! 

I'm curious if there's any plan that can be shared.

Dagre has many longstanding core algorithm issues and lack of customizability. I'm especially curious if there's intention to improve those.

(I make https://github.com/terrastruct/d2 , a diagramming language. We offer dagre as a layout option, but have [shimmed](https://github.com/terrastruct/d2/blob/master/d2layouts/d2dagrelayout/layout.go) it quite a bit)

**Comment by rustedgrail** [comment]
The primary goal is to modernise the libraries, removing deprecated dependencies, old code patterns, fixing security issues, etc. After that, I'll take a look at expanding the library.

However, I'm open to PRs and have merged the ones that came in recently. Any new feature requests will get looked at as soon as I get around to it and if it's minor, implemented and released soon.

If there is an older PR you're interested in reviving, let me know and I'll see about merging or reimplementing it.

**Comment by aloisklink** [comment]
> The primary goal is to modernise the libraries, removing deprecated dependencies, old code patterns, fixing security issues

There's also https://github.com/tbo47/dagre-es, that's primarily an updated ESM version of `dagre-d3`, but it comes with ESM versions of `dagre` and `graphlib`.

There's also some other changes, like we've migrated most of the `dagre` and `graphlib` tests over to `vitest`, a more modern test runner (although we're still missing browser tests).

It's under the same MIT license as the original `dagre`, so you're welcome to copy over the updated code! Because it's ESM-only, and the API is a different, it's not backwards compatible however, so it would need a **MAJOR** version bump though.

**Comment by rustedgrail** [comment]
Thanks for the heads up! I'll take a look and copy what I can.

**Comment by jlaine** [comment]
The current situation is highly confusing:

- there are no tags for the recent releases: the last tag is for version 0.7.3, so it's hard to know what's on NPM
- the wiki still references using `npm install dagre`, not `npm install @dagrejs/dagre`

**Comment by rustedgrail** [comment]
I updated the wiki and latest release tag on GitHub

**Comment by jlaine** [comment]
Thanks @rustedgrail !
